import type { ExecutionContext } from '@nestjs/common';
import type { Reflector } from '@nestjs/core';
import { mock } from 'vitest-mock-extended';
import { AppException } from '../../common/errors/app.exception.js';
import { JwtAuthGuard } from './jwt-auth.guard.js';

// Parent class generated by AuthGuard('jwt'); stub canActivate so real Passport never runs.
const passportGuard = Object.getPrototypeOf(JwtAuthGuard.prototype) as {
  canActivate: (context: ExecutionContext) => unknown;
};

describe('JwtAuthGuard', () => {
  const context = mock<ExecutionContext>();

  afterEach(() => {
    vi.restoreAllMocks();
  });

  function setup(isPublic: boolean | undefined) {
    const reflector = mock<Reflector>();
    reflector.getAllAndOverride.mockReturnValue(isPublic);
    const parent = vi.spyOn(passportGuard, 'canActivate').mockReturnValue(true);
    return { guard: new JwtAuthGuard(reflector), parent };
  }

  it('bỏ qua kiểm tra token khi route có @Public()', () => {
    const { guard, parent } = setup(true);
    expect(guard.canActivate(context)).toBe(true);
    expect(parent).not.toHaveBeenCalled();
  });

  it('bắt buộc xác thực khi route không public', () => {
    const { guard, parent } = setup(undefined);
    expect(guard.canActivate(context)).toBe(true);
    expect(parent).toHaveBeenCalledOnce();
  });

  it('handleRequest ném lại lỗi từ validateUser', () => {
    const { guard } = setup(false);
    const locked = new AppException('AUTH_ACCOUNT_LOCKED');
    expect(() => guard.handleRequest(locked, false)).toThrow(locked);
  });

  it('handleRequest trả AUTH_UNAUTHORIZED khi thiếu token', () => {
    const { guard } = setup(false);
    expect(() =>
      guard.handleRequest(null, false, new Error('No auth token')),
    ).toThrow(expect.objectContaining({ code: 'AUTH_UNAUTHORIZED' }));
  });

  it('handleRequest trả AUTH_SESSION_INVALID khi token sai hoặc hết hạn', () => {
    const { guard } = setup(false);
    expect(() =>
      guard.handleRequest(null, false, new Error('jwt expired')),
    ).toThrow(expect.objectContaining({ code: 'AUTH_SESSION_INVALID' }));
    expect(() => guard.handleRequest(null, false)).toThrow(
      expect.objectContaining({ code: 'AUTH_SESSION_INVALID' }),
    );
  });
});
